version: "3.9"

services:
  app:
    build: .
    image: 'zchuan/midi-tracker:latest'
    volumes:
      - .:/app
    ports:
      - "8080:8080"
    networks:
      default:
        ipv4_address: 172.31.32.206

networks:
  default:
    name: midi-tracker
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.31.32.0/20
          gateway: 172.31.32.1