version: "3.9"

services:
  app:
    build: .
    image: 'zchuan/midi-tracker:latest'
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    networks:
      - default

networks:
  default:
    name: midi-tracker
    driver: bridge